### What-If Simulation Engine

A reusable prediction function created to simulate how changes in study behavior and educational factors affect predicted final exam scores. Inputs are standardized using the saved scaler before being passed into the trained regression model.

In [1]:
import pandas as pd
import pickle

In [2]:
with open("../models/random_forest_model.pkl", "rb") as f:
    model = pickle.load(f)

In [3]:
student_data = {
    "Study_Hours_per_Week": 35,
    "Attendance_Rate": 60,
    "Past_Exam_Scores": 95,
    "Parental_Education_Level": 2,
    "Internet_Access_at_Home": 1,
    "Extracurricular_Activities": 1
}

In [4]:
input_df = pd.DataFrame([student_data])

input_df

,Study_Hours_per_Week,Attendance_Rate,Past_Exam_Scores,Parental_Education_Level,Internet_Access_at_Home,Extracurricular_Activities
0,35,60,95,2,1,1

,Study_Hours_per_Week,Attendance_Rate,Past_Exam_Scores,Parental_Education_Level,Internet_Access_at_Home,Extracurricular_Activities
0,35,60,95,2,1,1

In [5]:
prediction = model.predict(input_df)

prediction

array([59.53])

array([59.53])

In [6]:
def predict_score(
    study_hours,
    attendance,
    past_scores,
    parental_education,
    internet_access,
    extracurricular
):
    
    student_data = {
        "Study_Hours_per_Week": study_hours,
        "Attendance_Rate": attendance,
        "Past_Exam_Scores": past_scores,
        "Parental_Education_Level": parental_education,
        "Internet_Access_at_Home": internet_access,
        "Extracurricular_Activities": extracurricular
    }
    
    input_df = pd.DataFrame([student_data])
    
    prediction = model.predict(input_df)
    
    return prediction[0]

In [7]:
predict_score(
    study_hours= 30,
    attendance= 90,
    past_scores= 85,
    parental_education=2,
    internet_access=1,
    extracurricular=1
)

np.float64(66.54)

np.float64(66.54)

Scenario testing showed that increasing study hours produced noticeable improvements in predicted final scores. This demonstrates the simulator’s ability to model the potential impact of behavioral and academic changes on student performance.